### PR TITLE
Refine icon

### PR DESCRIPTION
**Pull request by t32k**
I refined LiceCap icon. Please use it if you like it.
https://github.com/t32k/licecap-icon

### CODE REVIEW

**Comment by nicolasmccurdy** [comment]
:+1:

**Comment by ichord** [comment]
:+1:

**Comment by nicolasmccurdy** [comment]
I really like this icon, and I think it would be great for the Mac app, but I'm not sure if this would fit in with Windows' icon theme.

**Comment by nicolasmccurdy** [comment]
Also, is the gray border at the top of the PNG icon intentional?

**Comment by gido** [comment]
:+1: and we found this [icon art work](https://dribbble.com/shots/1663619-LICEcap-Replacement-Icon) by @cjdowner

**Comment by guillaumeberry** [comment]
:+1:

**Comment by cjdowner** [comment]
By all means, feel free to use this icon. It was made quite quickly though. I'm sure you can save out the PNGs from the ICNS file and apply it to the .ICO

**Comment by li-xinyang** [comment]
:+1:

**Comment by 1000ch** [comment]
:100: 

I hope that re-opened!

**Pull request closed without merging**
